name: MobPlugin
main: creeperCZ.mobplugin.MobPlugin
version: "1.0"
api: ["1.0.0"]

load: STARTUP
author: milk0417, kniffo80, CreeperFace, PikyCZ, NycuRO, caspervanneck, woofie
description: Implement Entity AI from scratch beginning with 0.16.x
website: hhttps://pikycz.github.io/MobPlugin/

commands:
  mob:
    description: Spawn a simple mob to the player, that is using this command
    usage: "/mob spawn <mob_name>"
    permission: mob-plugin.command
  removemobs:
    description: Remove all living mobs
    usage: "/mob removeall"
    permission: mob-plugin.command
  testpath:
    description: Calculates a path
    usage: "/testpath"
    permission: mob-plugin.command

permissions:
  mob-plugin.command:
    description: ""
    default: op
